### ISSUE TITLE
LoadFirstResourceLanguageAgnostic: 0xC0070715

### ISSUE THREAD

**Issue by alexfreu69** [smx-smx/wcpex#2]
I'm trying to decrpyt a manifest file (amd64_hyperv-commandline-tool_31bf3856ad364e35_10.0.19041.1741_none_a1948794377af8a5.manifest for example) on Windows 10 21H2 with a 64 bit wcp.dll, build 10.0.19421.2180.
This fails with 

Size: 228
Type is 4
InitializeDeltaCompressor: 0x00000000
LoadFirstResourceLanguageAgnostic: 0xC0070715
LoadFirstResourceLanguageAgnostic failed

0xC0070715 = ERROR_RESOURCE_TYPE_NOT_FOUND

LoadFirstResourceLanguageAgnostic is called with 0x266. Could it be a different "magic number" now? How did you identify it?

**Comment by alexfreu69** [comment]
Found the solution myself:

The constant is still 0x266, but the declaration of the parameters needs to be changed:

````
static long (__fastcall *LoadFirstResourceLanguageAgnostic)(
	unsigned long unused,
	HINSTANCE hModule,
	unsigned short const *lpType,
	unsigned short const *lpName,
	void *pOutDict
);

````
	result = LoadFirstResourceLanguageAgnostic(
		0, //unused
		wcp, //HMODULE

		// These seem to have a special meaning
		//0x266, //lpType (unsure)
		(void *)0x266,
		(void *)1, //unknown

		&DictData
	);
    
Identified it with WinDbg and the following command:

````
0:005> x wcp!*LoadFirst*
00007ffe`1fcae148 wcp!Windows::Rtl::LoadFirstResourceLanguageAgnostic (long __cdecl Windows::Rtl::LoadFirstResourceLanguageAgnostic(unsigned long,struct HINSTANCE__ *,wchar_t const *,wchar_t const *,struct _LBLOB *))
00007ffe`1fe698c0 wcp!Windows::Rtl::LoadFirstResourceLanguageAgnostic (long __cdecl Windows::Rtl::LoadFirstResourceLanguageAgnostic(unsigned long,struct HINSTANCE__ *,unsigned short const *,unsigned short const *,struct _LBLOB *))

**Comment by McNinjaTNT** [comment]
@alexfreu69 Sorry for the bother, but would you be willing to send me a compiled executable? I'm having a really hard time compiling this project at all using cmake.
Cool stuff figuring out that issue btw, goes right over my head haha.

**Comment by alexfreu69** [comment]
@McNinjaTNT 

I've created a fork and uploaded a release. Hope that helps.

https://github.com/alexfreu69/wcpex/releases

**Comment by McNinjaTNT** [comment]
Thanks so much! Appreciate it

**Comment by smx-smx** [comment]
@alexfreu69 Thanks for fixing it! and sorry for the late reply.
Do you want to send a pull request?

**Comment by smx-smx** [comment]
Thanks, I'll review it soon. Meanwhile i wanted to let you know that i have another (newer) variant of the program here: https://github.com/smx-smx/Winternals/blob/603fddc1431a7ddde135005016ffa84c519a5da6/WinSxS/internals/undelta.cpp

**Comment by smx-smx** [comment]
Merged, thanks! 🙂 
Let me know if the problem persists
